export const JOI_INVALID_EMAIL_ERROR = `"email" must be a valid email`;
export const JOI_SHORT_PASSWORD_ERROR = `"password" length must be at least 8 characters long`;
export const JOI_NONE_STRING_PASSWORD = `"password" must be a string`;
export const JOI_NONE_STRING_USERNAME = `"username" must be a string`;
export const JOI_NONE_STRING_EMAIL = `"email" must be a string`;
export const JOI_ALPHANUMERIC_ERROR = `'"password" must only contain alpha-numeric characters'`;
export const JOI_PASSWORD_REQUIRED = `"password" is required`;
export const JOI_USERNAME_REQUIRED = `"username" is required`;
export const JOI_EMAIL_REQUIRED = `"email" is required`;
