language: node_js
node_js:
  - "stable"
services:
  - postgresql
notifications:
  email: false
  slack: andela:m0fSBLRd944nk3Gme63A9OgD
rvm:
  - 2.2.0
script:
   - "node ./node_modules/.bin/nyc check-coverage --statements 90 --branches 90 --lines 90 --functions 90"
before_script:
  - psql -c 'create database titan_devs_test' -U postgres
  - yarn
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
