language: node_js
node_js:
  - "stable"
notifications:
  email: false
  slack: 
    andela:m0fSBLRd944nk3Gme63A9OgD
env:
  global:
    - CC_TEST_REPORTER_ID=97b70dada289f07ea85b3a24ebcb83f91886f7f73c448df84071430fb75b9af6
rvm:
  - 2.2.0
before_script:
  - yarn install
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script:
  - bundle exec rspec
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
